easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Article
#       - App\Entity\Category
#       - App\Entity\User

    user:
        display_name: true
        name_property_path: 'firstName'
