<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU6bScuL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU6bScuL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU6bScuL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU6bScuL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU6bScuL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U6bScuL',
    'container.build_id' => 'c7bd5b61',
    'container.build_time' => 1551178953,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU6bScuL');
