<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSlKdJxK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSlKdJxK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSlKdJxK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSlKdJxK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSlKdJxK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SlKdJxK',
    'container.build_id' => 'e913d7a0',
    'container.build_time' => 1552746116,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSlKdJxK');
